---
- name: my web server
  hosts: all
  become: True
  tasks:
    - name: install httpd
      yum: 
        name: httpd
        state: latest

    - name: start and enable httpd service
      service:
        name: httpd
        state: started

    - name: deploy html app
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
...