---
- name: line in file
  hosts: all
  become: True
  tasks:
    - name: replace line 
      lineinfile:
            path: /var/www/html/index.html
            regexp: "^<h1> Hello World </h1>"
            line: "<h1> Hello World is changed </h1>"
...