---
- name: variable example
  hosts: all
  vars:
     URL: "smitkotkar42@gmail.com"
  tasks:
    - name: locally declare
      debug:
        msg: "{{URL}}"
      vars:
        URL: "google.com"
    - name: Print another URL
      debug:
        msg: "{{URL}}"
    - name: Smit Kotkar
      debug: 
        msg: "{{URL}}"
      vars:
        URL: "smitkotkar.com"
...
