---
- name: variable example
  hosts: all
  vars:
     URL: "CBZ.google.com"
  vars_files:
    - ./variable.txt
  tasks:
  - name: Print url
    debug:
      msg: "{{URL}}"
  - name: Print 2nd url
    debug:
      msg: "{{URL}}"
...
