---
- name: install httpd
  hosts: all
  become: True
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest
    - name: start httpd
      systemd:
        name: httpd
        state: started
...